Hooks:PostHook(PlayerTweakData, "_init_new_stances", "zm_init_new_stances", function(self)
    self.stances.nothing2_primary = deep_clone(self.stances.default)
    self.stances.nothing2_primary.standard.shoulders.translation = Vector3(1, 999999999, 0.2)
    self.stances.nothing2_primary.crouched.shoulders.translation = Vector3(1, 999999999, -0.2)

	self.stances.wunderwaffe_primary = deep_clone(self.stances.default)
	local pivot_shoulder_translation = Vector3(10.5287, 10.4677, 0.247723)
	local pivot_shoulder_rotation = Rotation(0.000398715, -0.000868289, -0.000330621)
	local pivot_head_translation = Vector3(10, 14, 1)
	local pivot_head_rotation = Rotation(0, 0, 0)
	self.stances.wunderwaffe_primary.standard.shoulders.translation = Vector3(-0.777, 5.503, 4.127)
	self.stances.wunderwaffe_primary.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
	self.stances.wunderwaffe_primary.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -86, 0)
	local pivot_head_translation = Vector3(0, 20, 0)
	local pivot_head_rotation = Rotation(0, 0, 0)
	self.stances.wunderwaffe_primary.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
	self.stances.wunderwaffe_primary.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
	self.stances.wunderwaffe_primary.steelsight.zoom_fov = false
	self.stances.wunderwaffe_primary.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -50, 0)
	self.stances.wunderwaffe_primary.steelsight.vel_overshot.yaw_neg = 0
	self.stances.wunderwaffe_primary.steelsight.vel_overshot.yaw_pos = -0
	self.stances.wunderwaffe_primary.steelsight.vel_overshot.pitch_neg = -0
	self.stances.wunderwaffe_primary.steelsight.vel_overshot.pitch_pos = 0
	local pivot_head_translation = Vector3(9, 13, -1)
	local pivot_head_rotation = Rotation(0, 0, 0)
	self.stances.wunderwaffe_primary.crouched.shoulders.translation = Vector3(-0.777, 5.503, 4.127)
	self.stances.wunderwaffe_primary.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
	self.stances.wunderwaffe_primary.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -36, 0)

	self.stances.wunderwaffe_secondary = deep_clone(self.stances.wunderwaffe_primary)
	self.stances.wunderwaffe_dg3_primary = deep_clone(self.stances.wunderwaffe_primary)
	self.stances.wunderwaffe_dg3_secondary = deep_clone(self.stances.wunderwaffe_primary)
	self.stances.colt_1911_primary = deep_clone(self.stances.colt_1911)
	self.stances.colt_1911_secondary = deep_clone(self.stances.colt_1911)
	self.stances.new_m14_primary = deep_clone(self.stances.new_m14)
	self.stances.new_m14_secondary = deep_clone(self.stances.new_m14)
	self.stances.new_m14_upg_primary = deep_clone(self.stances.new_m14)
	self.stances.new_m14_upg_primary.steelsight.shoulders.translation = Vector3(-0.04, 0, -3.87)
	self.stances.new_m14_upg_secondary = deep_clone(self.stances.new_m14)
	self.stances.new_m14_upg_secondary.steelsight.shoulders.translation = Vector3(-0.04, 0, -3.87)
	self.stances.b682_primary = deep_clone(self.stances.b682)
	self.stances.b682_secondary = deep_clone(self.stances.b682)
	self.stances.mp9_primary = deep_clone(self.stances.mp9)
	self.stances.mp9_secondary = deep_clone(self.stances.mp9)
end)
